In [1]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\masri\Downloads\4_8_df_classical.csv")
df

,Title,Composer,Year,Opus_Number,Key,Tempo,Time_Signature,Number_of_Movements,Length
0,Symphony No. 5,Ludwig van Beethoven,1808,Op. 67,C Minor,Allegro con brio,"(4, 4)",4,35
1,Symphony No. 9,Ludwig van Beethoven,1824,Op. 125,D Minor,Allegro ma non troppo,"(4, 4)",4,70
2,The Magic Flute (Die Zauberflöte),Wolfgang Amadeus Mozart,1791,K. 620,D Major,Allegro,"(4, 4)",2,120
3,"Piano Sonata No. 14 ""Moonlight""",Ludwig van Beethoven,1801,Op. 27 No. 2,C# Minor,Adagio sostenuto,"(4, 4)",3,15
4,Requiem in D Minor,Wolfgang Amadeus Mozart,1791,K. 626,D Minor,Lacrimosa,"(4, 4)",2,45
...,...,...,...,...,...,...,...,...,...
178,Violin Concerto in C Major,Joseph Haydn,1783,Hob. VIIa/1,C Major,Allegro,"(4, 4)",3,40
179,Piano Sonata in A Major,Johannes Brahms,1853,Op. 2,A Major,Allegro,"(4, 4)",4,30
180,Symphony No. 6 in F Major,Ludwig van Beethoven,1808,Op. 68,F Major,Allegro ma non troppo,"(4, 4)",5,45
181,Symphony No. 3 in E-flat Major,Joseph Haydn,1794,Hob. I/3,E-flat Major,Allegro,"(4, 4)",4,50
182,Piano Concerto No. 1 in C Major,Piotr Illich Tchaikovsky,1875,Op. 23,C Major,Allegro,"(4, 4)",3,40

In [2]:
# How many rows are in data frame
print(df.shape)
df.duplicated().sum()

(183, 9)

np.int64(40)

In [3]:
#Excluding duplicated rows, how many works in df were written by Beethoven?
df.loc[~df.duplicated() & 
                 (df["Composer"] == "Ludwig van Beethoven")].shape[0]

30

In [4]:
#The Romantic time period can roughly be defined by the years 1850-1920 inclusive. 
#Excluding duplicate rows, how many pieces were in this time frame?

df.loc[~df.duplicated() & 
                (df["Year"].between(1850,1920))].shape[0]

56

In [11]:
#Including duplicates, how many pieces were written in a Major key?

df[df["Key"].str.contains("Major")].shape[0]

102

In [12]:
# Including duplicates, how many pieces were written in a sharp key? Sharps can be denoted using the word "sharp" or "#".


df[df["Key"].str.contains("sharp|#", case=False)].shape[0]

5

In [14]:
#How many different Time Signatures are present in df?


df["Time_Signature"].nunique()

3

In [15]:
#Suppose you were to binge listen to every song in df including duplicates. 
#How many minutes would this take you assuming the data in the DataFrame is stored in minutes?

df["Length"].sum()

np.int64(8977)

In [20]:
#  Length of the piece with the largest number of movements

df.loc[df["Number_of_Movements"].idxmax(), "Length"]

np.int64(50)

In [21]:
# Count of digits 1 and 2 in all titles

df["Title"].str.count("1|2").sum()

np.int64(54)

In [1]:
#From the df_classical DataFrame, create a new DataFrame df_final where all data is the same,
#except the "Composer" column is changed so that it only includes the last name of each composer.

df_final = df.copy()
df_final["Composer"] = df_final["Composer"].str.split().str[-1]

NameError: name 'df' is not defined

In [23]:
#Modify the given df DataFrame to include a column for Period corresponding to the table above for each work in the table. 
#Do the modification in place.


df.loc[df["Year"].between(1400, 1600), "Period"] = "Renaissance"
df.loc[df["Year"].between(1601, 1750), "Period"] = "Baroque"
df.loc[df["Year"].between(1751, 1820), "Period"] = "Classical"
df.loc[df["Year"].between(1821, 1900), "Period"] = "Romantic"
df.loc[df["Year"].between(1901, 2000), "Period"] = "20th Century"
df.loc[df["Year"] >= 2001, "Period"] = "Contemporary"

In [24]:
df

,Title,Composer,Year,Opus_Number,Key,Tempo,Time_Signature,Number_of_Movements,Length,Period
0,Symphony No. 5,Ludwig van Beethoven,1808,Op. 67,C Minor,Allegro con brio,"(4, 4)",4,35,Classical
1,Symphony No. 9,Ludwig van Beethoven,1824,Op. 125,D Minor,Allegro ma non troppo,"(4, 4)",4,70,Romantic
2,The Magic Flute (Die Zauberflöte),Wolfgang Amadeus Mozart,1791,K. 620,D Major,Allegro,"(4, 4)",2,120,Classical
3,"Piano Sonata No. 14 ""Moonlight""",Ludwig van Beethoven,1801,Op. 27 No. 2,C# Minor,Adagio sostenuto,"(4, 4)",3,15,Classical
4,Requiem in D Minor,Wolfgang Amadeus Mozart,1791,K. 626,D Minor,Lacrimosa,"(4, 4)",2,45,Classical
...,...,...,...,...,...,...,...,...,...,...
178,Violin Concerto in C Major,Joseph Haydn,1783,Hob. VIIa/1,C Major,Allegro,"(4, 4)",3,40,Classical
179,Piano Sonata in A Major,Johannes Brahms,1853,Op. 2,A Major,Allegro,"(4, 4)",4,30,Romantic
180,Symphony No. 6 in F Major,Ludwig van Beethoven,1808,Op. 68,F Major,Allegro ma non troppo,"(4, 4)",5,45,Classical
181,Symphony No. 3 in E-flat Major,Joseph Haydn,1794,Hob. I/3,E-flat Major,Allegro,"(4, 4)",4,50,Classical
182,Piano Concerto No. 1 in C Major,Piotr Illich Tchaikovsky,1875,Op. 23,C Major,Allegro,"(4, 4)",3,40,Romantic