In [1]:
import pandas as pd
df= pd.read_csv(r"C:\Users\masri\Downloads\4_1_3_CC.csv")

C:\Users\masri\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df.head()

,Planet,Year,Avg_Temperature,Max_Temperature,Min_Temperature,Atmospheric_Pressure,Orbital_Distance,Distance_from_Nearest_Planet
0,Earth,2026,24.904780,159.932684,-78.714188,1684,2.793840,9.679047
1,Mars,2023,-27.892936,268.807586,-198.160590,1019,13.078108,5.524922
2,Venus,2027,222.931879,571.454852,-179.705691,1320,20.779597,4.292362
3,Jupiter,2024,10.538997,261.601466,-67.299646,1775,2.122530,5.728351
4,Saturn,2026,-23.579471,359.395311,-198.987683,1511,27.490326,5.801653

In [3]:
df.tail()

,Planet,Year,Avg_Temperature,Max_Temperature,Min_Temperature,Atmospheric_Pressure,Orbital_Distance,Distance_from_Nearest_Planet
67,HD 85512 b,2027,237.328762,489.937773,-37.977321,1950,20.909555,2.562369
68,Mercury,2026,-146.871541,421.015823,-26.585536,1345,10.710763,3.369500
69,HD 85512 b,2028,79.836286,142.069982,-17.351889,1740,28.124785,4.401073
70,Mercury,2027,37.834951,180.814357,-97.731520,1473,1.559915,2.611454
71,HD 85512 b,2024,-50.051485,549.277094,-99.696741,1116,12.771203,4.111501

In [4]:
df.shape

(72, 8)

In [5]:
df.columns

Index(['Planet', 'Year', 'Avg_Temperature', 'Max_Temperature',
       'Min_Temperature', 'Atmospheric_Pressure', 'Orbital_Distance',
       'Distance_from_Nearest_Planet'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Planet                        72 non-null     str
 1   Year                          72 non-null     int64
 2   Avg_Temperature               72 non-null     float64
 3   Max_Temperature               72 non-null     float64
 4   Min_Temperature               72 non-null     float64
 5   Atmospheric_Pressure          72 non-null     int64
 6   Orbital_Distance              72 non-null     float64
 7   Distance_from_Nearest_Planet  72 non-null     float64
dtypes: float64(5), int64(2), str(1)
memory usage: 5.2 KB

In [7]:
df.describe()

,Year,Avg_Temperature,Max_Temperature,Min_Temperature,Atmospheric_Pressure,Orbital_Distance,Distance_from_Nearest_Planet
count,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000
mean,2024.736111,67.660982,347.998596,-91.010114,1523.666667,14.802769,5.439738
std,2.752684,131.969147,146.903434,58.274525,303.811330,8.737829,2.747419
min,2020.000000,-147.515047,108.293914,-198.987683,1004.000000,0.853014,0.629504
25%,2022.750000,-47.137913,221.002263,-141.153074,1266.750000,7.311239,3.288772
50%,2025.000000,67.352367,353.693020,-85.303495,1607.500000,15.156745,5.514744
75%,2027.000000,196.969337,463.260423,-40.310247,1783.000000,20.812086,7.527530
max,2029.000000,294.099121,592.825227,-1.989230,1992.000000,29.393512,9.959719

In [8]:
df.isna().sum()

Planet                          0
Year                            0
Avg_Temperature                 0
Max_Temperature                 0
Min_Temperature                 0
Atmospheric_Pressure            0
Orbital_Distance                0
Distance_from_Nearest_Planet    0
dtype: int64

In [9]:
df["Planet"].unique()

<ArrowStringArray>
[             'Earth',               'Mars',              'Venus',
            'Jupiter',             'Saturn',             'Uranus',
            'Neptune',              'Pluto', 'Proxima Centauri b',
         'Kepler-22b',        'Gliese 581g',        'HD 209458 b',
        'TRAPPIST-1d',         'Kepler-62f',        'Kepler-186f',
         'LHS 1140 b',           'WASP-12b',        'HD 189733 b',
           'WASP-43b',          'WASP-107b',            'Mercury',
         'HD 85512 b']
Length: 22, dtype: str

In [10]:
df["Planet"].value_counts()

Planet
Mercury               6
HD 85512 b            6
Earth                 3
Mars                  3
Venus                 3
Jupiter               3
Saturn                3
Uranus                3
Neptune               3
Pluto                 3
Proxima Centauri b    3
Kepler-22b            3
Gliese 581g           3
HD 209458 b           3
TRAPPIST-1d           3
Kepler-62f            3
Kepler-186f           3
LHS 1140 b            3
WASP-12b              3
HD 189733 b           3
WASP-43b              3
WASP-107b             3
Name: count, dtype: int64

In [11]:
df

,Planet,Year,Avg_Temperature,Max_Temperature,Min_Temperature,Atmospheric_Pressure,Orbital_Distance,Distance_from_Nearest_Planet
0,Earth,2026,24.904780,159.932684,-78.714188,1684,2.793840,9.679047
1,Mars,2023,-27.892936,268.807586,-198.160590,1019,13.078108,5.524922
2,Venus,2027,222.931879,571.454852,-179.705691,1320,20.779597,4.292362
3,Jupiter,2024,10.538997,261.601466,-67.299646,1775,2.122530,5.728351
4,Saturn,2026,-23.579471,359.395311,-198.987683,1511,27.490326,5.801653
...,...,...,...,...,...,...,...,...
67,HD 85512 b,2027,237.328762,489.937773,-37.977321,1950,20.909555,2.562369
68,Mercury,2026,-146.871541,421.015823,-26.585536,1345,10.710763,3.369500
69,HD 85512 b,2028,79.836286,142.069982,-17.351889,1740,28.124785,4.401073
70,Mercury,2027,37.834951,180.814357,-97.731520,1473,1.559915,2.611454
71,HD 85512 b,2024,-50.051485,549.277094,-99.696741,1116,12.771203,4.111501

In [12]:
df.shape[0]

72

In [15]:
df.shape[1]

8

In [17]:
#how many columns starts wuth letter "M"   


# sum(df.columns.str.startswith("M"))
sum(df.columns.str.startswith("M"))

np.int64(2)

In [23]:
df.head(15)
sum(df.head(15)["Year"] == 2026)

3

In [24]:
#Of the last 15 rows, how many have an atmospheric pressure measurement less than 1200?
df.tail(15)
sum(df.tail(15)["Atmospheric_Pressure"]<1200)

4

In [26]:
#How many columns store integers (int64)?

df.select_dtypes(include="int64").shape[1]

2

In [27]:
#What is the mean average temperature correct to two decimal places? 
round(df["Avg_Temperature"].mean(), 2)

np.float64(67.66)