In [2]:
import pandas as pd    

df= pd.read_csv(r"C:\Users\masri\Downloads\Student_grade.csv")
print(df)

       Name  Student ID  Grade
0     Alice    10000001     98
1       Bob    10000002     87
2     Carol    10000003     91
3     David    10000004     78
4       Eva    10000005     85
5     Frank    10000006     92
6     Grace    10000007     67
7      Hank    10000008     80
8       Ivy    10000009     47
9      Jack    10000010     95
10    Kathy    10000011     83
11      Leo    10000012     90
12     Mona    10000013     77
13     Nina    10000014     88
14    Oscar    10000015     92
15     Paul    10000016     85
16   Quincy    10000017     80
17     Rita    10000018     78
18      Sam    10000019     89
19     Tina    10000020     39
20   Ursula    10000021     56
21   Victor    10000022     84
22    Wendy    10000023     61
23   Xander    10000024     77
24     Yara    10000025     89
25     Zane    10000026     95
26    Aaron    10000027     70
27    Bella    10000028     82
28  Charlie    10000029     88
29    Diana    10000030     94

In [3]:
g = 90
df.query("`Grade`>= @g")

     Name  Student ID  Grade
0   Alice    10000001     98
2   Carol    10000003     91
5   Frank    10000006     92
9    Jack    10000010     95
11    Leo    10000012     90
14  Oscar    10000015     92
25   Zane    10000026     95
29  Diana    10000030     94

In [ ]:
df.query("`Grade` >= {0}".format(g))

In [ ]:
df.query(f"`Grade` >= {g}")

In [ ]:
df.query("`Grade` >= {0}".format(g))

In [4]:
df.query("`Grade` >=90 and `Grade` <=95")

     Name  Student ID  Grade
2   Carol    10000003     91
5   Frank    10000006     92
9    Jack    10000010     95
11    Leo    10000012     90
14  Oscar    10000015     92
25   Zane    10000026     95
29  Diana    10000030     94

In [8]:
df.query("`Name` in ["Joe", "Bob"]")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2504226473.py, line 1)

In [6]:
df.query("Name.str.contains("Bea"))

SyntaxError: unterminated string literal (detected at line 1) (2693701745.py, line 1)

In [11]:
print(df.filter(["Name", "Grade"]))

       Name  Grade
0     Alice     98
1       Bob     87
2     Carol     91
3     David     78
4       Eva     85
5     Frank     92
6     Grace     67
7      Hank     80
8       Ivy     47
9      Jack     95
10    Kathy     83
11      Leo     90
12     Mona     77
13     Nina     88
14    Oscar     92
15     Paul     85
16   Quincy     80
17     Rita     78
18      Sam     89
19     Tina     39
20   Ursula     56
21   Victor     84
22    Wendy     61
23   Xander     77
24     Yara     89
25     Zane     95
26    Aaron     70
27    Bella     82
28  Charlie     88
29    Diana     94

In [12]:
print(df.filter(like="de"))

    Student ID  Grade
0     10000001     98
1     10000002     87
2     10000003     91
3     10000004     78
4     10000005     85
5     10000006     92
6     10000007     67
7     10000008     80
8     10000009     47
9     10000010     95
10    10000011     83
11    10000012     90
12    10000013     77
13    10000014     88
14    10000015     92
15    10000016     85
16    10000017     80
17    10000018     78
18    10000019     89
19    10000020     39
20    10000021     56
21    10000022     84
22    10000023     61
23    10000024     77
24    10000025     89
25    10000026     95
26    10000027     70
27    10000028     82
28    10000029     88
29    10000030     94

In [13]:
print(df.filter(regex="e$"))

       Name  Grade
0     Alice     98
1       Bob     87
2     Carol     91
3     David     78
4       Eva     85
5     Frank     92
6     Grace     67
7      Hank     80
8       Ivy     47
9      Jack     95
10    Kathy     83
11      Leo     90
12     Mona     77
13     Nina     88
14    Oscar     92
15     Paul     85
16   Quincy     80
17     Rita     78
18      Sam     89
19     Tina     39
20   Ursula     56
21   Victor     84
22    Wendy     61
23   Xander     77
24     Yara     89
25     Zane     95
26    Aaron     70
27    Bella     82
28  Charlie     88
29    Diana     94

In [15]:
print(df.filter(list(range(0,len(df), 2)), axis=0))

       Name  Student ID  Grade
0     Alice    10000001     98
2     Carol    10000003     91
4       Eva    10000005     85
6     Grace    10000007     67
8       Ivy    10000009     47
10    Kathy    10000011     83
12     Mona    10000013     77
14    Oscar    10000015     92
16   Quincy    10000017     80
18      Sam    10000019     89
20   Ursula    10000021     56
22    Wendy    10000023     61
24     Yara    10000025     89
26    Aaron    10000027     70
28  Charlie    10000029     88

In [30]:
print(df)

       Name  Student ID  Grade
0     Alice    10000001     98
1       Bob    10000002     87
2     Carol    10000003     91
3     David    10000004     78
4       Eva    10000005     85
5     Frank    10000006     92
6     Grace    10000007     67
7      Hank    10000008     80
8       Ivy    10000009     47
9      Jack    10000010     95
10    Kathy    10000011     83
11      Leo    10000012     90
12     Mona    10000013     77
13     Nina    10000014     88
14    Oscar    10000015     92
15     Paul    10000016     85
16   Quincy    10000017     80
17     Rita    10000018     78
18      Sam    10000019     89
19     Tina    10000020     39
20   Ursula    10000021     56
21   Victor    10000022     84
22    Wendy    10000023     61
23   Xander    10000024     77
24     Yara    10000025     89
25     Zane    10000026     95
26    Aaron    10000027     70
27    Bella    10000028     82
28  Charlie    10000029     88
29    Diana    10000030     94

In [27]:
#example of at
df.at[4, "Grade"]

np.int64(85)

In [29]:
#example of iat
df.iat[5, 2]

np.int64(92)

In [33]:
#example of loct
df.loc[3:28, ["Name", "Grade"]]

       Name  Grade
3     David     78
4       Eva     85
5     Frank     92
6     Grace     67
7      Hank     80
8       Ivy     47
9      Jack     95
10    Kathy     83
11      Leo     90
12     Mona     77
13     Nina     88
14    Oscar     92
15     Paul     85
16   Quincy     80
17     Rita     78
18      Sam     89
19     Tina     39
20   Ursula     56
21   Victor     84
22    Wendy     61
23   Xander     77
24     Yara     89
25     Zane     95
26    Aaron     70
27    Bella     82
28  Charlie     88

In [36]:
#example of loc
specific_value = df.loc[2, 'Student ID']
print(specific_value)

10000003

In [37]:
#exapmle of iloc
df.iloc[0:6, [0, 2]]

    Name  Grade
0  Alice     98
1    Bob     87
2  Carol     91
3  David     78
4    Eva     85
5  Frank     92

In [38]:
for idx, row in df.iterrows():
    print(idx, row["Name"], row["Grade"])

0 Alice 98
1 Bob 87
2 Carol 91
3 David 78
4 Eva 85
5 Frank 92
6 Grace 67
7 Hank 80
8 Ivy 47
9 Jack 95
10 Kathy 83
11 Leo 90
12 Mona 77
13 Nina 88
14 Oscar 92
15 Paul 85
16 Quincy 80
17 Rita 78
18 Sam 89
19 Tina 39
20 Ursula 56
21 Victor 84
22 Wendy 61
23 Xander 77
24 Yara 89
25 Zane 95
26 Aaron 70
27 Bella 82
28 Charlie 88
29 Diana 94